### PR TITLE
Fix 'treat NaN as invalid number'

### PR DESCRIPTION
**Pull request by jgpacheco**

### CODE REVIEW

**Comment by sebastianbarfurth** [comment]
The number check is doubled here. Take a look at the Polyfill here: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite

Use isFinite instead, we’re basically doing the Polyfill anyways.

**Comment by sebastianbarfurth** [comment]
Possibly a flag on the rule should allow infinite numbers?

**Comment by imbrn** [comment]
As the flag will be optional, I think we can make it latter.

**Comment by imbrn** [comment]
Closes #76

**Comment by imbrn** [comment]
This cannot be published in version `v1.2.0` because it introduces a breaking change. If someone have trusted in the `number` rule as a verification which allows `NaN` or `Infinity`, now it's going to break his/her code.

So this change should be included just in the next major release: 2.0.0

Maybe we should implement rules to check for `NaN` and `Infinity` values.

**Comment by sebastianbarfurth** [comment]
Why not add an option to number that specifies whether to include infinite numbers? Default it to true until 2.0 is out and then default it to false. So the rule would simply take an argument

**Comment by imbrn** [comment]
I do not like the idea of introducing flags to rules. I know that in the `number` rule that's not a big deal; even so, the readability of the rule becomes not obvious:

```javascript
v8n().number(false);
```

**Comment by sebastianbarfurth** [comment]
Joa about a modifier then? Call it infinite. Or something.

**Comment by imbrn** [comment]
A modifier would look much more readable, but do you think it's worth adding a modifier just to be used with the number rule? It's so much more expensive to define a modifier than a rule.

**Comment by imbrn** [comment]
I know that the `number` rule should become strict to only finite numbers, but we can't do that until 2.0 anyway. So I think, for now, we should stick with the `finite` rule and in the next major release, we can think better about that.

**Comment by sebastianbarfurth** [comment]
Well that is what it is, a rule tends be useful in more than one context. A finite rule would be absolutely useless unless used specially with number.

**Comment by imbrn** [comment]
We're running out of options. But as a `number` rule is supposed to be used almost always for finite numbers, maybe the `flag` thing is not the worst choice, since after version 2.0 it'll be almost never used anyway.

**Comment by sebastianbarfurth** [comment]
I actually do agree with your readability thinking. I just feel that infinite numbers will be so incredibly rarely used that the low weight of a flag is a great option.

Adding a finite rule for now actually might be fine, we just need to mark it as deprecated right away.

I like both approaches. I lean toward the flag for size reasons.

**Comment by imbrn** [comment]
Yeah, that's right! So we should go with the `flag` option to solve this. But we must make it default to allow NaN and Infinity values for now, at least until version 2.

@jgpacheco could you do that?

**Comment by sebastianbarfurth** [comment]
Yeah default allow until 2.0.0

**Comment by jgpacheco** [comment]
@imbrn Sure!

**Comment by imbrn** [comment]
@sebastianbarfurth can you update the CHANGELOG file with the modifications and deprecations about this `rule`?

**Pull request merged**
