### PR TITLE
Add modifier for strict schema validation

### PR DESCRIPTION
**Pull request by barfurth**
## Description

This adds a modifier `strict` that can be used with the `schema` rule. All it does it ensure that a validated schema has no additional properties. This makes a strict schema validation more locked down than comparable coding paradigms like interfaces.

Thank you @dbismut for the idea.

Part of #191, inspired by #179

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please, feel free to specify what kind of change it is)

## Checklist:

- [x] I have created my branch from a recent version of `master`
- [x] The code is clean and easy to understand
- [x] I have written tests to guarantee that everything is working properly
- [x] I have made corresponding changes to the documentation
- [x] I have added changes to the `Unreleased` section of the CHANGELOG

### CODE REVIEW

**Comment by barfurth** [comment]
For you to note @imbrn: Every modifier function can now also use the rule it is being validated on. The rule is passed to the modifier as a second argument. This change is backward compatible. This allows modifiers to act based on the rule they are on and even to validate based on the arguments given to the rule. This is important for this modifier, because it needs to change the outcome of the validation based on the configuration of the `schema` rule.

**Review by imbrn — APPROVED** [review]
It seems really good to me.

I'd like to have some other tests using other modifiers together, for example:

```ts
.not.strict
.not.some.strict
.some.not.strict
// etc
```

It'd be nice to also have some test to check that `strict` is actually ignored by not-schema-based validations.

**Comment by barfurth** [comment]
@imbrn I have added more tests - what do you think?

**Review by imbrn — APPROVED** [review]
Really nice! 🤩

**Pull request merged**
