### PR TITLE
Switch to typescript

### LINKED ISSUE #28: Support TypeScript
Thank you!

### PR DESCRIPTION
**Pull request by brfrth**
## Description

Rewrote all the files in typescript. This adds native support for any typescript applications. I tried to keep the API the same, but that would need to be verified. It would need to be checked if this is a breaking change.

Fixes #28 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have made corresponding changes to the documentation
- [ ] I have added changes to the `Unreleased` section of the CHANGELOG

### CODE REVIEW

**Comment by brfrth** [comment]
Still working on the new build pipeline.

**Comment by brfrth** [comment]
@imbrn Please explain https://github.com/imbrn/v8n/blob/master/src/Rule.js#L29 to me. What is it for? It appears difficult to type and is very non-clear.

**Comment by imbrn** [comment]
@brfrth actually, I think we shouldn't go with an entire refactor for using Typescript by now. But instead just releasing a version with a `v8n.d.ts` file. I know it'd be amazing to change the codebase for using that, but it's not that easy as most of the library is dynamic and runtime generated behavior. So starting with only this types file could give us more time and confidence for future refactoring.

What do you think?

**Comment by brfrth** [comment]
Sure, I guess TS would be more of a 2.0 feature. I still want to grasp what exactly that second call to `testAux` does.

**Pull request closed without merging**
