### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by barfurth**
This pull request contains necessary changes to release 1.4.0.

### CODE REVIEW

**Review by imbrn — APPROVED** [review]

**Comment by ev-akarel** [comment]
@barfurth / @imbrn What's the expected timeframe for this release?

**Comment by barfurth** [comment]
> @barfurth / @imbrn What's the expected timeframe for this release?

I don't think I can release (at least to npm) - so sadly I don't know. I was hoping it would be quick.

**Comment by imbrn** [comment]
Sorry everyone, I've been really busy lately and I haven't found enough time to work on the project.

Actually, I'd like to automate the deploying process end-to-end (maybe migrating that to Github Actions) so that we can have new versions deployed more often and automatically. 

I'll try to work on that this weekend.

**Comment by ev-akarel** [comment]
@imbrn Just went to NPM and the v8n pacakge is still showing v1.3.3 as the latest. Do you know when you might be able to get v1.4.0 pushed out?

**Comment by barfurth** [comment]
@ev-akarel version `1.4.0` is [now available on npm](https://www.npmjs.com/package/v8n/v/1.4.0). @imbrn

**Pull request merged**
