### PR TITLE
Add ability to return all errors from validation as array

### PR DESCRIPTION
**Pull request by sebastianbarfurth**
Related to issue #24.

This will add the ability to receive information about every failed rule in the validation instead of failing fast once any error happens.

```javascript
v8n()
  .number()
  .between(5, 10)
  .testAll(true); // [Rule { name: 'number', ... }, Rule  { name: 'between', ... }]

v8n()
  .number()
  .between(5, 10)
  .testAll(7); // []
```

The implementation is fairly straightforward.

### CODE REVIEW

**Comment by imbrn** [comment]
Looks great!

**Comment by sebastianbarfurth** [comment]
@imbrn Added for review.

**Comment by imbrn** [comment]
The code is great.

Maybe you want to rebase it into master?

**Comment by sebastianbarfurth** [comment]
Merged again.

**Comment by imbrn** [comment]
Great!

**Comment by imbrn** [comment]
It closes #24

**Pull request merged**
