### PR TITLE
Move optionalAsync into optional

### LINKED ISSUE #206: Using optionality and asynchronous rules in the same chain
I would like to be able to write something like this chain of validations:

`v8n().optional(v8n().email().checkEmailAvailable())`

`email` – regular rule for email validation (pattern) 
`checkEmailAvailable` – async rule

But right now it's not possible because inside optional rule we use `.check` strategy.

Is there a chance that this behavior can be implemented?

### PR DESCRIPTION
**Pull request by barfurth**
## Description

I noticed that we actually support rules that are both async and non-async based on the validation strategy used. The new, unreleased `optionalAsync` rule has been moved into the async branch of the `optional` rule for a more seamless experience. I've taken over the documentation example from the `optionalAsync` rule. 

Changes #223 
Fixes #206 

## Type of change

- [x] Other (please, feel free to specify what kind of change it is)

Modification of new rule.

## Checklist:

- [x] I have created my branch from a recent version of `master`
- [x] The code is clean and easy to understand
- [x] I have written tests to guarantee that everything is working properly
- [x] I have made corresponding changes to the documentation
- [x] I have added changes to the `Unreleased` section of the CHANGELOG

### CODE REVIEW

**Review by imbrn — APPROVED** [review]
Really good work, @barfurth .  👏

It looks much more readable and easy to use than `optionalAsync`.

Only have to fix the conflicts. Thank you!

**Comment by barfurth** [comment]
@imbrn I remember we talked about the `dist` files in #180. With out new build process I believe we don't need this anymore. Releases contain a proper bundle that people can download, so `dist` files aren't necessary. What do you think about no longer comitting them?

**Comment by imbrn** [comment]
@barfurth , I like the idea of removing the `dist` folder from the source repository. But, as far as I know, the release assets are just the files included in the repository (in a compressed format), although I think we can include files during the build process, I'm not sure about that.

**Comment by barfurth** [comment]
Yeah we can add the release bundle to the release assets. I will make a PR for that including the removal of the `dist` files.

**Pull request merged**
