### PR TITLE
Manually deploy dispatching for GH Actions

### PR DESCRIPTION
**Pull request by imbrn**
## Description

Adds a Github Action workflow trigger that permits manually deploy dispatching (npm publish).

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

## Type of change

- [x] Other (please, feel free to specify what kind of change it is)

## Checklist:

- [x] I have created my branch from a recent version of `master`

### CODE REVIEW

**Comment by barfurth** [comment]
What exactly is the purpose of this? Shouldn't a release trigger the release - what's the point in doing it manually?

**Comment by imbrn** [comment]
Yeah, I agree with you that the release creation should trigger this action.

But as we had a problem with the 1.4.0 version deployment using CircleCI, and it's not deployed to npm yet, I was trying to force this deploy from GH action instead.

I could do that manually from my machine, but I'd like to test the new deployment mechanisms using GH.

If you think it's actually a real problem to have this manual option enabled, we can revert this PR after the release is released. What do you think?

**Comment by barfurth** [comment]
It's reasonable to test I think. In this case I would agree that it can be enabled for now and then be disabled again.

Also I believe instead of enabling a manual deploy we you could add more options to the triggers for a release (e.g. `released`). Then deleting the GitHub release (and the tag) and creating it again should trigger it. The tag just has to be at the HEAD.

Manual trigger is fine though, I just don't think it makes sense to keep.

On a side note: is the stable branch still used?

**Comment by imbrn** [comment]
I really liked the ideia of having a `released` trigger instead. I'll read a little more about it. Thank you for the suggestion.

About the `stable` branch, I'd like to discontinue it. It was only used to keep the Github README version pointing to the latest published version instead of master. But I don't like this separation anyway.

**Comment by imbrn** [comment]
@barfurth agree?

**Comment by barfurth** [comment]
Yeah, more triggers can be added in the future (example: prerelease). Looks good now.

**Review by barfurth — APPROVED** [review]

**Pull request merged**
